
symbols = [
  "^BTC-[0-9]{1,2}[A-Z]{3}[0-9]{2}$",  # futures
#  "^ETH-[0-9]{1,2}[A-Z]{3}[0-9]{2}$",  # futures
#  "^SOL-[0-9]{1,2}[A-Z]{3}[0-9]{2}$",  # futures
#  "^XRP-[0-9]{1,2}[A-Z]{3}[0-9]{2}$",  # futures
   "^BTC(_USD[A-Z]?)?-PERPETUAL$",      # swaps
  "^ETH(_USD[A-Z]?)?-PERPETUAL$",      # swaps
  "^SOL(_USD[A-Z]?)?-PERPETUAL$",      # swaps
  "^XRP(_USD[A-Z]?)?-PERPETUAL$",      # swaps 
#  "^BCH(_USD[A-Z]?i)?-PERPETUAL$",      # swaps
  "^TRX(_USD[A-Z]?)?-PERPETUAL$",      # swaps
  "^ADA(_USD[A-Z]?)?-PERPETUAL$",      # swaps
  "^LINK(_USD[A-Z]?)?-PERPETUAL$",      # swaps
  "^LTC(_USD[A-Z]?)?-PERPETUAL$",      # swaps
  "^ALGO(_USD[A-Z]?)?-PERPETUAL$",      # swaps
  "^NEAR(_USD[A-Z]?)?-PERPETUAL$",      # swaps
  "^DOT(_USD[A-Z]?)?-PERPETUAL$",      # swaps
  "^AVAX(_USD[A-Z]?)?-PERPETUAL$",      # swaps
#   "^BTC(-USD[A-Z]?)?-DERIBIT-INDEX$",  # index
#  "^ETH(-USD[A-Z]?)?-DERIBIT-INDEX$",   # index
#  "^SOL(-USD[A-Z]?)?-DERIBIT-INDEX$"   # index
]

[accounts]

  [accounts.A1]
  master = true
  login = "Kt5jFNmB"
  secret = "zu4TCDww6evj_pjy2Fj1LLa0Fxpqcq3VqcmsjzxZHYA"
  symbols = [ ".*" ]

[users]

  [users.test]
  password = "1234"
  symbols = ".*"

  [users.trader]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ ".*ADA.*", ".*LINK.*", ".*LTC.*" , ".*TRX.*",  ".*ALGO.*",  ".*XRP.*",   ".*NEAR.*" ]

  [users.simon]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ ".*DOT.*",".*ADA.*", ".*LINK.*", ".*LTC.*" , ".*TRX.*", ".*ALGO.*",   ".*NEAR.*" ]

  [users.BCH]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ ".*ADA.*", ".*LINK.*", ".*LTC.*" , ".*TRX.*", ".*ALGO.*",   ".*NEAR.*" ]

  
  [users.trader2]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ ".*ADA.*", ".*LINK.*", ".*LTC.*" , ".*TRX.*", ".*ALGO.*",   ".*NEAR.*" ]

  [users.linus]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ ".*BTC.*", ".*ETH.*", ".*SOL.*"]

  [users.BTC-ETH_d-o]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ ".*BTC.*", ".*ETH.*"]

  [users.BTC-SOL_d-o]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ ".*BTC.*", ".*SOL.*"]

  [users.LTC_FR]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ ".*LTC.*"]

  [users.DOT_FR]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ ".*DOT.*"]

  [users.LINK_FR]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ ".*LINK.*"]

  [users.BTC_term_front]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ ".*BTC.*"]

  [users.ALGO_FR]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [".*ALGO.*"]

  [users.TRX_FR]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [".*TRX.*"]

  [users.AVAX_FR]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [".*AVAX.*"]

[rate_limits] 
  
  [rate_limits.global]
    type = "ORDER_ACTION"
    aggregate = true
    request_limit = 100
    monitor_period = "4s"
    ban_period = "5m"
