symbols = ".*"

[users]

  [users.trader]
  password = "secret"

  [users.simon]
  password = "secret"

  [users.ALGO_FR]
  password = "secret"

  [users.LTC_FR]
  password = "secret"

  [users.SWEAT]
  password = "secret"

  [users.ENS]
  password = "secret"

  [users.RAY]
  password = "secret" 
